SOURCES = [
    {
        "name": "ET Insurance",
        "url": "https://economictimes.indiatimes.com/industry/banking/insurance/rssfeeds/13358259.cms",
        "type": "rss",
        "priority": "high",
        "tags": ["Market", "Industry"],
    },
    {
        "name": "LiveMint Insurance",
        "url": "https://www.livemint.com/rss/insurance",
        "type": "rss",
        "priority": "high",
        "tags": ["Market", "Industry"],
    },
    {
        "name": "BusinessLine",
        "url": "https://www.thehindubusinessline.com/economy/rss?id=421446",
        "type": "rss",
        "priority": "medium",
        "tags": ["Market", "Industry"],
    },
    {
        "name": "MoneyControl Insurance",
        "url": "https://www.moneycontrol.com/rss/insurance.xml",
        "type": "rss",
        "priority": "medium",
        "tags": ["Market", "Industry"],
    },
    {
        "name": "Google News - IRDAI",
        "url": "https://news.google.com/rss/search?q=IRDAI+insurance+India&hl=en-IN&gl=IN&ceid=IN:en",
        "type": "rss",
        "priority": "high",
        "tags": ["IRDAI", "Regulation"],
    },
    {
        "name": "Google News - Insurance India",
        "url": "https://news.google.com/rss/search?q=insurance+India+broking&hl=en-IN&gl=IN&ceid=IN:en",
        "type": "rss",
        "priority": "high",
        "tags": ["Market", "Industry"],
    },
    {
        "name": "Google News - MFI Insurance",
        "url": "https://news.google.com/rss/search?q=microfinance+insurance+India&hl=en-IN&gl=IN&ceid=IN:en",
        "type": "rss",
        "priority": "high",
        "tags": ["MFI", "Microfinance"],
    },
    {
        "name": "Google News - Group Health",
        "url": "https://news.google.com/rss/search?q=group+health+insurance+India+IRDAI&hl=en-IN&gl=IN&ceid=IN:en",
        "type": "rss",
        "priority": "high",
        "tags": ["Group Health", "IRDAI"],
    },
    {
        "name": "IRDAI Press Releases",
        "url": "https://irdai.gov.in/press-releases",
        "type": "scrape",
        "priority": "high",
        "tags": ["IRDAI", "Regulation"],
    },
    {
        "name": "IRDAI Circulars",
        "url": "https://irdai.gov.in/circulars",
        "type": "scrape",
        "priority": "high",
        "tags": ["IRDAI", "Regulation"],
    },
]
